name: taxi_driver
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.1+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # BASE
  intl: ^0.18.1
  google_fonts: ^6.2.1
  html: ^0.15.4
  shared_preferences: ^2.2.2
  flutter_widget_from_html: ^0.15.1
  flutter_background_service: ^1.0.0

  # TOAST
  fluttertoast: ^8.2.4

  # IMAGE
  cached_network_image: ^3.3.0

  # UI
  sliding_up_panel: ^2.0.0+1
  dotted_line: ^3.2.2
  lottie: ^3.1.2
  flutter_rating_bar: ^4.0.1
  flutter_staggered_animations: ^1.1.1
  bottom_picker: ^2.3.2
  country_code_picker: ^3.0.0
  flutter_native_contact_picker: any
  timeline_tile: ^2.0.0
  flutter_vector_icons: ^2.0.0
  flutter_switch: ^0.3.2
  syncfusion_flutter_charts: ^26.2.9

  #OTP TEXT FIELD
  otp_text_field: ^1.1.3

  #MAP
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  google_maps_flutter: ^2.9.0
  flutter_polyline_points: ^2.0.0
  location: ^6.0.2
  flutter_compass: ^0.8.0
  gmaps_by_road_distance_calculator: ^2.0.6

  #IMAGES
  image_picker: ^1.0.4
  file_picker: ^8.0.7
  date_time_picker: ^2.1.0

  #CONNECTIVITY
  package_info_plus: ^8.0.0
  http: ^1.1.0
  connectivity_plus: ^6.0.5
  url_launcher: ^6.2.1
  map_launcher: ^3.0.1

  #FIREBASE
  firebase_crashlytics: ^3.4.18
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  firebase_storage: ^11.6.9
  firebase_database: ^10.3.4
  paginate_firestore: ^1.0.3+1
  cloud_firestore: ^4.13.1

  #STATE MANAGEMENT
  mobx: ^2.2.1
  flutter_mobx: ^2.1.1

  #PAYMENT GATEWAY


  # PUSH NOTIFICATION
  onesignal_flutter: ^5.2.9

  #SOCIAL LOGIN
  google_sign_in: ^6.1.6
  the_apple_sign_in: ^1.1.1

  #MQTT
  mqtt_client: ^10.3.0

  #DOWNLOAD INVOICE PDF
  pdf: ^3.10.8
  path_provider: ^2.1.1
  open_file: ^3.3.2
  printing: ^5.11.1
  flutter_ringtone_player: ^4.0.0+3

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.6
  mobx_codegen: ^2.4.0
  #flutter packages pub run build_runner build --delete-conflicting-outputs

dependency_overrides:
  intl: ^0.18.0
  cloud_firestore: ^4.8.1
  http: ^1.0.0
  chewie: ^1.5.0


flutter:

  uses-material-design: true

  assets:
    - images/
    - images/icons/
    - images/flag/
    - images/ringtone.mp3
